services:

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports: 
    - 8080:8080
    volumes:
    - ./nginx/nginx.conf.main:/etc/nginx/nginx.conf:ro #ro is readonly, ie nginx cant modify it
    depends_on:
    - app_blue
    - app_green


  app_blue:
    image: chaos:2.0
    container_name: blue_depl
    environment:
      PORT: 8081
      POOL_NAME: blue
      RELEASE_ID: ${RELEASE_ID_BLUE}
    ports:
    - 8081:8081
  app_green:
    image: chaos:2.0
    container_name: green_depl
    environment:
      PORT: 8082
      POOL_NAME: green
      RELEASE_ID: ${RELEASE_ID_GREEN}
    ports:
    - 8082:8082