events {
    worker_connections 1024; #this configures how nginx hnadles connections, it is the max number of simultaneous connections a worker process will have
}

http {
    upstream app_backend { #this creates a group of servers, the name can be anything
        server app_blue:8081 max_fails=3 fail_timeout=10s; #this is the blue server, "app_blue:8081" service name and port. 
        #max_fails tells nginx to mark this server as down after that max number of failure, fail_timeout is the amount of time to consider 
        #server as down before trying to send a connection to it again
        server app_green:8082 backup; #backup here is a keyword to tell nginx to only use green when blue is down, if this isnt there
        #nginx will try to load balance requests between the two servers
    }

    server{
        listen 8080; #tells nginx to listen on port 8080

        location / { # handles all requests on all routes, version, chaos, health etc
            proxy_pass http://app_backend; # forwards the request to the backend upstream server group
            proxy_next_upstream error timeout http_500 http_502 http_503; # this literally means, try the next upstream server if the current server returns any of these errors
            proxy_next_upstream_tries 2; #maximum amount of upstream servers to try before returning an error, if it is set to 1, we get an error immediately after blue fails and we dont want that
            proxy_next_upstream_timeout 10s; maximum time nignx will spend trying all different upstream servers for a single request, this prevents retry loops, thereby preventing the client from waiting forever
            # so, onnce blue fails, green fails, an error is returned, no need trying to test blue again, once 10s is exceeded no more chececking even if there may be server active, if the request doesnt get a reponse before 10s, error out
            proxy_connect_timeout 2s; #Max time to establish connection to a backend server, if after 2s a response isnt gotten from the server, mark that particular server as down and check the next
            proxy_send_timeout 2s; # Max time to waits to send request to backend, this helps to check frozen or overloaded servers
            proxy_read_timeout 2s; # Max time to wait for backend to respond
            # the above three lines sets tight timeouts so failures are detected quickly
        }
    }
}